resolver: lts-10.4
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 53ca8948f08819129b41ec6211d7ae0fd0f9d66a
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
