resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 48353c256452dee75ee8da5620d7eb55f98b7de5
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
