resolver: lts-10.4
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 843bcdca4abc1393076e3ae69d750af095ed7d59
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
